from typing import Any
class dtype: ...
class device: ...
class Tensor:
    shape: tuple[int, ...]
    dtype: dtype
    device: device
    ndim: int
    def numel(self) -> int: ...
    def dim(self) -> int: ...
    def size(self, dim: int | None = ...) -> Any: ...
    def item(self) -> Any: ...
    def contiguous(self) -> Tensor: ...
    def reshape(self, *shape: int) -> Tensor: ...
    def view(self, *shape: int) -> Tensor: ...
    def transpose(self, dim0: int, dim1: int) -> Tensor: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
float16: dtype
float32: dtype
float64: dtype
int8: dtype
int16: dtype
int32: dtype
int64: dtype
uint8: dtype
bool: dtype
def empty(*size: Any, **kwargs: Any) -> Tensor: ...
def zeros(*size: Any, **kwargs: Any) -> Tensor: ...
def ones(*size: Any, **kwargs: Any) -> Tensor: ...
def full(size: Any, fill_value: Any, **kwargs: Any) -> Tensor: ...
def rand(*size: Any, **kwargs: Any) -> Tensor: ...
def randn(*size: Any, **kwargs: Any) -> Tensor: ...
def tensor(data: Any, **kwargs: Any) -> Tensor: ...
def empty_like(input: Tensor, **kwargs: Any) -> Tensor: ...
def zeros_like(input: Tensor, **kwargs: Any) -> Tensor: ...
def ones_like(input: Tensor, **kwargs: Any) -> Tensor: ...
def full_like(input: Tensor, fill_value: Any, **kwargs: Any) -> Tensor: ...
def arange(*args: Any, **kwargs: Any) -> Tensor: ...
def exp(input: Tensor, **kwargs: Any) -> Tensor: ...
def log(input: Tensor, **kwargs: Any) -> Tensor: ...
def sqrt(input: Tensor, **kwargs: Any) -> Tensor: ...
def sigmoid(input: Tensor) -> Tensor: ...
def relu(input: Tensor) -> Tensor: ...
def tanh(input: Tensor) -> Tensor: ...
def sum(input: Tensor, *args: Any, **kwargs: Any) -> Tensor: ...
def mean(input: Tensor, *args: Any, **kwargs: Any) -> Tensor: ...
def max(input: Tensor, *args: Any, **kwargs: Any) -> Any: ...
def min(input: Tensor, *args: Any, **kwargs: Any) -> Any: ...
def cumsum(input: Tensor, dim: int, **kwargs: Any) -> Tensor: ...
def matmul(input: Tensor, other: Tensor, **kwargs: Any) -> Tensor: ...
def clamp(input: Tensor, min: Any = ..., max: Any = ...) -> Tensor: ...
def where(condition: Tensor, input: Any, other: Any) -> Tensor: ...
def __getattr__(name: str) -> Any: ...
