from typing import Any, Callable, TypeAlias
Array: TypeAlias = Any
def jit(fun: Callable[..., Any], **kwargs: Any) -> Any: ...
def vmap(fun: Callable[..., Any], **kwargs: Any) -> Any: ...
def __getattr__(name: str) -> Any: ...
