from typing import Any
class Module:
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def forward(self, *args: Any, **kwargs: Any) -> Any: ...
class Linear(Module):
    def __init__(self, in_features: int, out_features: int, bias: bool = ...) -> None: ...
class ReLU(Module): ...
class GELU(Module): ...
class Sequential(Module):
    def __init__(self, *modules: Module) -> None: ...
def __getattr__(name: str) -> Any: ...
