from typing import Any
from .. import Tensor
def relu(input: Tensor, inplace: bool = ...) -> Tensor: ...
def gelu(input: Tensor, approximate: str = ...) -> Tensor: ...
def softmax(input: Tensor, dim: int | None = ..., dtype: Any = ...) -> Tensor: ...
def __getattr__(name: str) -> Any: ...
