from typing import Any, Callable, Sequence
class Config:
    def __init__(self, kwargs: dict[str, Any], num_warps: int = ..., num_stages: int = ..., num_ctas: int = ...) -> None: ...
def jit(fn: Callable[..., Any] | None = ..., **kwargs: Any) -> Any: ...
def autotune(configs: Sequence[Config], key: Sequence[str], **kwargs: Any) -> Any: ...
def heuristics(values: dict[str, Any]) -> Any: ...
def cdiv(x: int, div: int) -> int: ...
def next_power_of_2(x: int) -> int: ...
def __getattr__(name: str) -> Any: ...
