from typing import Any, Callable
class Tensor:
    shape: Any
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
class Int32(int): ...
class Uint32(int): ...
class Float32(float): ...
def jit(fn: Callable[..., Any]) -> Any: ...
def ceil_div(a: Any, b: Any) -> Any: ...
def make_layout(shape: Any, stride: Any = ...) -> Any: ...
def make_tensor(iterator: Any, layout: Any) -> Tensor: ...
def copy(src: Any, dst: Any, **kwargs: Any) -> None: ...
def gemm(atom: Any, a: Any, b: Any, c: Any, **kwargs: Any) -> None: ...
def __getattr__(name: str) -> Any: ...
