from typing import Any
from .. import Array
class dtype: ...
float16: dtype
float32: dtype
float64: dtype
int32: dtype
int64: dtype
uint32: dtype
def array(value: Any, **kwargs: Any) -> Array: ...
def asarray(value: Any, **kwargs: Any) -> Array: ...
def empty(shape: Any, **kwargs: Any) -> Array: ...
def zeros(shape: Any, **kwargs: Any) -> Array: ...
def ones(shape: Any, **kwargs: Any) -> Array: ...
def full(shape: Any, fill_value: Any, **kwargs: Any) -> Array: ...
def arange(*args: Any, **kwargs: Any) -> Array: ...
def zeros_like(a: Array, **kwargs: Any) -> Array: ...
def full_like(a: Array, fill_value: Any, **kwargs: Any) -> Array: ...
def exp(x: Any) -> Array: ...
def log(x: Any) -> Array: ...
def sqrt(x: Any) -> Array: ...
def tanh(x: Any) -> Array: ...
def sum(x: Any, **kwargs: Any) -> Array: ...
def mean(x: Any, **kwargs: Any) -> Array: ...
def max(x: Any, **kwargs: Any) -> Array: ...
def min(x: Any, **kwargs: Any) -> Array: ...
def cumsum(x: Any, **kwargs: Any) -> Array: ...
def maximum(x: Any, y: Any) -> Array: ...
def minimum(x: Any, y: Any) -> Array: ...
def where(condition: Any, x: Any, y: Any) -> Array: ...
def matmul(x: Any, y: Any, **kwargs: Any) -> Array: ...
def __getattr__(name: str) -> Any: ...
